/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PromotionRouteImport } from './routes/promotion'
import { Route as ProhibitedRouteImport } from './routes/prohibited'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddListingRouteImport } from './routes/add-listing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as ProfileListingsRouteImport } from './routes/profile/listings'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPendingRouteImport } from './routes/admin.pending'
import { Route as AdminMessageReportsRouteImport } from './routes/admin.message-reports'
import { Route as ProfileListingsIdRouteImport } from './routes/profile/listings.$id'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionRoute = PromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitedRoute = ProhibitedRouteImport.update({
  id: '/prohibited',
  path: '/prohibited',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddListingRoute = AddListingRouteImport.update({
  id: '/add-listing',
  path: '/add-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileListingsRoute = ProfileListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ProfileRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessageReportsRoute = AdminMessageReportsRouteImport.update({
  id: '/message-reports',
  path: '/message-reports',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileListingsIdRoute = ProfileListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfileListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRoute
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/prohibited': typeof ProhibitedRoute
  '/promotion': typeof PromotionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/admin/message-reports': typeof AdminMessageReportsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listings/$id': typeof ListingsIdRoute
  '/profile/listings': typeof ProfileListingsRouteWithChildren
  '/seller/$id': typeof SellerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/profile/listings/$id': typeof ProfileListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/prohibited': typeof ProhibitedRoute
  '/promotion': typeof PromotionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/admin/message-reports': typeof AdminMessageReportsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listings/$id': typeof ListingsIdRoute
  '/profile/listings': typeof ProfileListingsRouteWithChildren
  '/seller/$id': typeof SellerIdRoute
  '/admin': typeof AdminIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/profile/listings/$id': typeof ProfileListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRoute
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/prohibited': typeof ProhibitedRoute
  '/promotion': typeof PromotionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/admin/message-reports': typeof AdminMessageReportsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listings/$id': typeof ListingsIdRoute
  '/profile/listings': typeof ProfileListingsRouteWithChildren
  '/seller/$id': typeof SellerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/profile/listings/$id': typeof ProfileListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-listing'
    | '/admin'
    | '/categories'
    | '/chats'
    | '/favorites'
    | '/listings'
    | '/login'
    | '/more'
    | '/notifications'
    | '/offers'
    | '/privacy'
    | '/profile'
    | '/prohibited'
    | '/promotion'
    | '/reset-password'
    | '/safety'
    | '/saved-searches'
    | '/support'
    | '/terms'
    | '/verification'
    | '/admin/message-reports'
    | '/admin/pending'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/verifications'
    | '/auth/callback'
    | '/listings/$id'
    | '/profile/listings'
    | '/seller/$id'
    | '/admin/'
    | '/listings/'
    | '/profile/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-listing'
    | '/categories'
    | '/chats'
    | '/favorites'
    | '/login'
    | '/more'
    | '/notifications'
    | '/offers'
    | '/privacy'
    | '/profile'
    | '/prohibited'
    | '/promotion'
    | '/reset-password'
    | '/safety'
    | '/saved-searches'
    | '/support'
    | '/terms'
    | '/verification'
    | '/admin/message-reports'
    | '/admin/pending'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/verifications'
    | '/auth/callback'
    | '/listings/$id'
    | '/profile/listings'
    | '/seller/$id'
    | '/admin'
    | '/listings'
    | '/profile/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/add-listing'
    | '/admin'
    | '/categories'
    | '/chats'
    | '/favorites'
    | '/listings'
    | '/login'
    | '/more'
    | '/notifications'
    | '/offers'
    | '/privacy'
    | '/profile'
    | '/prohibited'
    | '/promotion'
    | '/reset-password'
    | '/safety'
    | '/saved-searches'
    | '/support'
    | '/terms'
    | '/verification'
    | '/admin/message-reports'
    | '/admin/pending'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/users'
    | '/admin/verifications'
    | '/auth/callback'
    | '/listings/$id'
    | '/profile/listings'
    | '/seller/$id'
    | '/admin/'
    | '/listings/'
    | '/profile/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddListingRoute: typeof AddListingRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ChatsRoute: typeof ChatsRoute
  FavoritesRoute: typeof FavoritesRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProhibitedRoute: typeof ProhibitedRoute
  PromotionRoute: typeof PromotionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SellerIdRoute: typeof SellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion': {
      id: '/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof PromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibited': {
      id: '/prohibited'
      path: '/prohibited'
      fullPath: '/prohibited'
      preLoaderRoute: typeof ProhibitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-listing': {
      id: '/add-listing'
      path: '/add-listing'
      fullPath: '/add-listing'
      preLoaderRoute: typeof AddListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/listings': {
      id: '/profile/listings'
      path: '/listings'
      fullPath: '/profile/listings'
      preLoaderRoute: typeof ProfileListingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/message-reports': {
      id: '/admin/message-reports'
      path: '/message-reports'
      fullPath: '/admin/message-reports'
      preLoaderRoute: typeof AdminMessageReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/listings/$id': {
      id: '/profile/listings/$id'
      path: '/$id'
      fullPath: '/profile/listings/$id'
      preLoaderRoute: typeof ProfileListingsIdRouteImport
      parentRoute: typeof ProfileListingsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMessageReportsRoute: typeof AdminMessageReportsRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMessageReportsRoute: AdminMessageReportsRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface ProfileListingsRouteChildren {
  ProfileListingsIdRoute: typeof ProfileListingsIdRoute
}

const ProfileListingsRouteChildren: ProfileListingsRouteChildren = {
  ProfileListingsIdRoute: ProfileListingsIdRoute,
}

const ProfileListingsRouteWithChildren = ProfileListingsRoute._addFileChildren(
  ProfileListingsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileListingsRoute: typeof ProfileListingsRouteWithChildren
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileListingsRoute: ProfileListingsRouteWithChildren,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddListingRoute: AddListingRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ChatsRoute: ChatsRoute,
  FavoritesRoute: FavoritesRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProhibitedRoute: ProhibitedRoute,
  PromotionRoute: PromotionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SellerIdRoute: SellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
