-- RAWAJ Taxonomy, Data & Search Foundation V1: domain-specific field registry expansion.
-- Keeps field keys stable while allowing each canonical leaf to choose only relevant rules.

insert into public.option_sets (key, name_ar, name_en, description_ar, description_en)
values
  ('product_authenticity', 'أصالة المنتج', 'Product authenticity', 'توصيف أصالة المنتج دون ادعاء توثيق من رواج.', 'Seller-declared authenticity; not platform authentication.'),
  ('fashion_audience', 'الفئة', 'Fashion audience', null, null),
  ('food_unit', 'وحدة المنتج الغذائي', 'Food unit', null, null),
  ('animal_gender', 'جنس الحيوان', 'Animal gender', null, null),
  ('education_delivery_mode', 'طريقة تقديم التعليم', 'Education delivery mode', null, null),
  ('service_pricing_unit', 'وحدة تسعير الخدمة', 'Service pricing unit', null, null),
  ('business_item_type', 'نوع الأصل التجاري', 'Business item type', null, null)
on conflict (key) do update set
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  description_ar = excluded.description_ar,
  description_en = excluded.description_en,
  updated_at = now();

insert into public.option_values (option_set_key, value_key, label_ar, label_en, sort_order)
values
  ('product_authenticity', 'original', 'أصلي حسب البائع', 'Seller-declared original', 10),
  ('product_authenticity', 'commercial', 'تجاري', 'Commercial / aftermarket', 20),
  ('product_authenticity', 'handmade', 'مصنوع يدويًا', 'Handmade', 30),
  ('product_authenticity', 'unknown', 'غير محدد', 'Unknown', 90),
  ('fashion_audience', 'men', 'رجالي', 'Men', 10),
  ('fashion_audience', 'women', 'نسائي', 'Women', 20),
  ('fashion_audience', 'kids', 'أطفال', 'Kids', 30),
  ('fashion_audience', 'unisex', 'للجميع', 'Unisex', 40),
  ('food_unit', 'g', 'غرام', 'Gram', 10),
  ('food_unit', 'kg', 'كيلوغرام', 'Kilogram', 20),
  ('food_unit', 'ml', 'ملليلتر', 'Milliliter', 30),
  ('food_unit', 'l', 'ليتر', 'Liter', 40),
  ('food_unit', 'piece', 'قطعة', 'Piece', 50),
  ('food_unit', 'pack', 'عبوة', 'Pack', 60),
  ('food_unit', 'box', 'صندوق', 'Box', 70),
  ('animal_gender', 'male', 'ذكر', 'Male', 10),
  ('animal_gender', 'female', 'أنثى', 'Female', 20),
  ('animal_gender', 'mixed', 'مختلط', 'Mixed', 30),
  ('animal_gender', 'unknown', 'غير محدد', 'Unknown', 90),
  ('education_delivery_mode', 'onsite', 'حضوري', 'On-site', 10),
  ('education_delivery_mode', 'online', 'أونلاين', 'Online', 20),
  ('education_delivery_mode', 'hybrid', 'حضوري وأونلاين', 'Hybrid', 30),
  ('service_pricing_unit', 'hour', 'بالساعة', 'Per hour', 10),
  ('service_pricing_unit', 'visit', 'بالزيارة', 'Per visit', 20),
  ('service_pricing_unit', 'day', 'باليوم', 'Per day', 30),
  ('service_pricing_unit', 'project', 'حسب المشروع', 'Per project', 40),
  ('service_pricing_unit', 'item', 'للقطعة', 'Per item', 50),
  ('service_pricing_unit', 'negotiated', 'حسب الاتفاق', 'Negotiated', 90),
  ('business_item_type', 'machine', 'آلة', 'Machine', 10),
  ('business_item_type', 'equipment', 'معدة', 'Equipment', 20),
  ('business_item_type', 'inventory', 'مخزون / بضاعة', 'Inventory', 30),
  ('business_item_type', 'shop', 'محل أو مشروع', 'Shop or business', 40),
  ('business_item_type', 'raw_material', 'مواد أولية', 'Raw material', 50),
  ('business_item_type', 'other', 'أخرى', 'Other', 90)
on conflict (option_set_key, value_key) do update set
  label_ar = excluded.label_ar,
  label_en = excluded.label_en,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.field_definitions (
  key,
  label_ar,
  label_en,
  description_ar,
  description_en,
  field_type,
  unit_key,
  option_set_key,
  data_provider_key,
  validation_schema,
  is_searchable,
  is_filterable,
  is_displayable,
  is_sensitive,
  sort_order
)
values
  ('product_brand', 'العلامة التجارية', 'Brand', null, null, 'text', null, null, null, '{"maxLength":100}'::jsonb, true, true, true, false, 700),
  ('product_model', 'الموديل أو الاسم', 'Model or product name', null, null, 'text', null, null, null, '{"maxLength":140}'::jsonb, true, true, true, false, 710),
  ('product_authenticity', 'أصالة المنتج', 'Product authenticity', 'معلومة يصرح بها البائع ولا تعني توثيق رواج للأصالة.', 'Seller-declared and not authenticated by RAWAJ.', 'single_select', null, 'product_authenticity', null, '{}'::jsonb, false, true, true, false, 720),
  ('quantity_available', 'الكمية المتوفرة', 'Quantity available', null, null, 'integer', 'piece', null, null, '{"minimum":1,"maximum":100000000}'::jsonb, false, true, true, false, 730),
  ('delivery_available', 'التوصيل متوفر', 'Delivery available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 740),
  ('warranty_available', 'يوجد ضمان', 'Warranty available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 750),
  ('material', 'الخامة أو المادة', 'Material', null, null, 'text', null, null, null, '{"maxLength":120}'::jsonb, true, true, true, false, 760),
  ('dimensions_text', 'الأبعاد', 'Dimensions', 'مثال: 200 × 90 × 80 سم.', 'Example: 200 × 90 × 80 cm.', 'text', null, null, null, '{"maxLength":120}'::jsonb, false, false, true, false, 770),
  ('pieces_count', 'عدد القطع', 'Pieces count', null, null, 'integer', 'piece', null, null, '{"minimum":1,"maximum":100000}'::jsonb, false, true, true, false, 780),
  ('assembly_available', 'التركيب متوفر', 'Assembly available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 790),
  ('battery_health_percent', 'صحة البطارية', 'Battery health', 'النسبة الظاهرة في إعدادات الجهاز إن كانت متاحة.', 'Device-reported percentage where available.', 'integer', 'percent', null, null, '{"minimum":0,"maximum":100}'::jsonb, false, true, true, false, 800),
  ('includes_box', 'العلبة الأصلية موجودة', 'Original box included', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 810),
  ('includes_charger', 'الشاحن موجود', 'Charger included', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 820),
  ('fashion_audience', 'الفئة', 'Audience', null, null, 'single_select', null, 'fashion_audience', null, '{}'::jsonb, true, true, true, false, 900),
  ('fashion_size', 'المقاس', 'Size', null, null, 'text', null, null, null, '{"maxLength":40}'::jsonb, true, true, true, false, 910),
  ('fashion_color', 'اللون', 'Color', null, null, 'text', null, null, null, '{"maxLength":80}'::jsonb, true, true, true, false, 920),
  ('food_quantity', 'الوزن أو الكمية', 'Weight or quantity', null, null, 'numeric', null, null, null, '{"minimum":0}'::jsonb, false, true, true, false, 1000),
  ('food_unit', 'الوحدة', 'Unit', null, null, 'single_select', null, 'food_unit', null, '{}'::jsonb, false, true, true, false, 1010),
  ('production_date', 'تاريخ الإنتاج', 'Production date', null, null, 'date', null, null, null, '{}'::jsonb, false, true, true, false, 1020),
  ('expiry_date', 'تاريخ الانتهاء', 'Expiry date', null, null, 'date', null, null, null, '{}'::jsonb, false, true, true, false, 1030),
  ('ingredients', 'المكونات', 'Ingredients', null, null, 'textarea', null, null, null, '{"maxLength":2000}'::jsonb, true, false, true, false, 1040),
  ('minimum_order', 'الحد الأدنى للطلب', 'Minimum order', null, null, 'numeric', null, null, null, '{"minimum":0}'::jsonb, false, true, true, false, 1050),
  ('animal_species', 'نوع الحيوان', 'Animal species', null, null, 'text', null, null, null, '{"maxLength":100}'::jsonb, true, true, true, false, 1100),
  ('animal_breed', 'السلالة', 'Breed', null, null, 'text', null, null, null, '{"maxLength":120}'::jsonb, true, true, true, false, 1110),
  ('animal_age_months', 'العمر', 'Age', null, null, 'integer', 'month', null, null, '{"minimum":0,"maximum":1200}'::jsonb, false, true, true, false, 1120),
  ('animal_gender', 'الجنس', 'Gender', null, null, 'single_select', null, 'animal_gender', null, '{}'::jsonb, false, true, true, false, 1130),
  ('vaccinated', 'اللقاحات مكتملة حسب البائع', 'Vaccinated according to seller', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 1140),
  ('health_certificate_available', 'شهادة صحية متوفرة', 'Health certificate available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 1150),
  ('education_subject', 'المادة أو المجال', 'Subject or field', null, null, 'text', null, null, null, '{"maxLength":140}'::jsonb, true, true, true, false, 1200),
  ('education_level', 'المستوى', 'Level', null, null, 'text', null, null, null, '{"maxLength":100}'::jsonb, true, true, true, false, 1210),
  ('education_delivery_mode', 'طريقة التقديم', 'Delivery mode', null, null, 'single_select', null, 'education_delivery_mode', null, '{}'::jsonb, true, true, true, false, 1220),
  ('session_duration_minutes', 'مدة الجلسة', 'Session duration', null, null, 'integer', 'minute', null, null, '{"minimum":1,"maximum":1440}'::jsonb, false, true, true, false, 1230),
  ('course_duration_text', 'مدة الدورة', 'Course duration', null, null, 'text', null, null, null, '{"maxLength":100}'::jsonb, false, false, true, false, 1240),
  ('certificate_available', 'شهادة متوفرة', 'Certificate available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 1250),
  ('years_experience', 'سنوات الخبرة', 'Years of experience', null, null, 'numeric', 'year', null, null, '{"minimum":0,"maximum":100}'::jsonb, false, true, true, false, 1300),
  ('home_visit_available', 'زيارة منزلية متوفرة', 'Home visit available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 1310),
  ('emergency_service_available', 'خدمة طارئة متوفرة', 'Emergency service available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 1320),
  ('service_pricing_unit', 'وحدة التسعير', 'Pricing unit', null, null, 'single_select', null, 'service_pricing_unit', null, '{}'::jsonb, false, true, true, false, 1330),
  ('service_warranty_available', 'ضمان على الخدمة', 'Service warranty available', null, null, 'boolean', null, null, null, '{}'::jsonb, false, true, true, false, 1340),
  ('business_item_type', 'نوع الأصل التجاري', 'Business item type', null, null, 'single_select', null, 'business_item_type', null, '{}'::jsonb, true, true, true, false, 1400),
  ('manufacture_year', 'سنة الصنع', 'Manufacture year', null, null, 'year', 'year', null, null, '{"minimum":1800,"maximum":2100}'::jsonb, false, true, true, false, 1410),
  ('country_of_origin', 'بلد المنشأ', 'Country of origin', null, null, 'text', null, null, null, '{"maxLength":100}'::jsonb, true, true, true, false, 1420),
  ('operating_hours', 'ساعات التشغيل', 'Operating hours', null, null, 'numeric', 'hour', null, null, '{"minimum":0}'::jsonb, false, true, true, false, 1430),
  ('power_specification', 'القدرة أو الطاقة', 'Power specification', null, null, 'text', null, null, null, '{"maxLength":120}'::jsonb, false, true, true, false, 1440),
  ('capacity_specification', 'الطاقة الإنتاجية أو السعة', 'Capacity specification', null, null, 'text', null, null, null, '{"maxLength":160}'::jsonb, false, true, true, false, 1450)
on conflict (key) do update set
  label_ar = excluded.label_ar,
  label_en = excluded.label_en,
  description_ar = excluded.description_ar,
  description_en = excluded.description_en,
  field_type = excluded.field_type,
  unit_key = excluded.unit_key,
  option_set_key = excluded.option_set_key,
  data_provider_key = excluded.data_provider_key,
  validation_schema = excluded.validation_schema,
  is_searchable = excluded.is_searchable,
  is_filterable = excluded.is_filterable,
  is_displayable = excluded.is_displayable,
  is_sensitive = excluded.is_sensitive,
  sort_order = excluded.sort_order,
  updated_at = now();
