-- DEPRECATED — DO NOT RUN
--
-- This legacy manual setup is intentionally non-executable.
-- It previously configured `listing-images` as a public bucket and created a
-- bucket-wide public SELECT policy. That model is superseded by RAWAJ's current
-- private-bucket and signed-URL architecture.
--
-- Current canonical requirements:
-- - `listing-images` remains private (`storage.buckets.public = false`).
-- - Owners keep scoped access to their own listing image objects.
-- - Public/anonymous object access must never be bucket-wide.
-- - Public access, where required for the current client flow, must be limited
--   to objects whose path resolves to an approved, non-archived listing.
-- - Moderation and hard-delete permissions must follow the canonical role model
--   defined by ordered repository migrations; this legacy file must not redefine them.
--
-- Historical path convention retained for documentation only:
--   {auth.uid()}/{listing_id}/{random-file-name}.{jpg|jpeg|png|webp}
--
-- Reconciliation belongs in an ordered migration under `supabase/migrations/`.
-- Do not restore the former `public = true` bucket setting or the former policy:
--   "RAWAJ listing images public read"
-- with condition:
--   bucket_id = 'listing-images'
